# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automatic Daily Enroller

on:
  workflow_dispatch:
  schedule:
  # Runs at 12am IST
  - cron: '30 18 */2 * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install udemy-enroller

    - name: Run crawler (Finalize)
      env:
        UDEMY_EMAIL: ${{ secrets.UDEMY_EMAIL }}
        UDEMY_PASSWORD: ${{ secrets.UDEMY_PASSWORD }}
        CI_TEST: "True"
      run: |
        udemy_enroller --max-pages=5 --debug --browser=chrome
